# Generated by Django 3.2.4 on 2021-06-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210621_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='process_status',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
