# Generated by Django 3.2.4 on 2021-06-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='education_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='job_status_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='language_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='prof_exp_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
